apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-factory-canary
  labels:
    app: api-factory
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-factory
      track: canary
  template:
    metadata:
      labels:
        app: api-factory
        track: canary
    spec:
      containers:
        - name: api-factory
          image: ghcr.io/your-org/api-factory:canary
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: API_KEY
              value: "devkey"
            - name: LOG_LEVEL
              value: "DEBUG"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
